spring:
  application:
    name: couriersync-backend

  graphql:
    schema:
      locations: classpath:graphql/
    graphiql:
      enabled: false
    path: /graphql

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.globally_quoted_identifiers: true

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true
    table: couriersync_flyway_history
    # baseline-on-migrate en false por defecto; se habilita manualmente SOLO al baselinar un entorno nuevo.
    baseline-on-migrate: false

sql:
  init:
    mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://tu-frontend.prod}
  graphql:
    limits:
      max-depth: 15
      max-complexity: 500

logging:
  level:
    # SQL visible por perfil; aquí base prudente
    org.hibernate.SQL: info
    # ✅ Hibernate 6:
    org.hibernate.orm.jdbc.bind: warn
