spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': false

  graphql:
    graphiql:
      enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    '[com.ep18.couriersync]': INFO
    '[org.springframework.security]': WARN
    '[org.hibernate]': WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"