spring:
  application:
    name: couriersync-backend

  # Perfil por defecto
  profiles:
    active: dev

  # GraphQL base
  graphql:
    schema:
      locations: classpath:graphql/
    graphiql:
      enabled: false   # habilita solo en dev
    path: /graphql

  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000       # 30s
      idle-timeout: 600000            # 10m
      max-lifetime: 1800000           # 30m (menor que el server-side idle)

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

app:
  graphql:
    limits:
      max-depth: 15
      max-complexity: 500

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: warn